language: node_js
dist: trusty
sudo: required
branches:
  only:
    - master
node_js:
  - "node"
  - "10"
cache:
  directories:
    - node_modules
install:
  - yarn
before_script:
  - sleep 15
  - yarn lint
script:
  - yarn test
after_success:
  - yarn coverage